DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Transaction;

CREATE TABLE User (
    Username TEXT PRIMARY KEY,
    Password TEXT,
);

CREATE TABLE Book (
    ID NUMERIC PRIMARY KEY,
    Title TEXT,
    Price INTEGER,
    SellerID TEXT,
    FOREIGN KEY (SellerID) REFERENCES User(Username)
);

CREATE TABLE Transaction (
    ID NUMERIC PRIMARY KEY,
    BookID NUMERIC,
    Date TEXT,
    BuyerID TEXT,
    FOREIGN KEY (BuyerID) REFERENCES User(Username),
    FOREIGN KEY (BookID) REFERENCES Book(ID)
);
